[package]
name = "optic-bridge-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
optic-bridge-core = { path = "../optic-bridge-core" }
process-wrap.workspace = true
thiserror.workspace = true
tokio.workspace = true
